name: Build Vue
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
        
    - name: install and build
      run: |
        npm ci
        npm run build
        ls build/
        
    - name: push to gh-pages
      run: |
        git config --global user.email "ze.zinho-2010@hotmail.com"
        git config --global user.name "Loukis-13"
        git config --global user.password ${{ secrets.GITHUB_TOKEN }}
        git add .
        git commit -m deploy
        git subtree push --prefix dist origin gh-pages
